<?php get_header(); ?>

<div class="content-gen legal total">	
	<section class="mod-legal total">    
	    <div class="container">
			<h1 class="title total">POLÍTICA DE PRIVACIDAD</h1>
			<h2>I.- Política de privacidad y protección de datos personales.</h2>
			<p>En el marco del cumplimiento de lo dispuesto en art 5 de la Ley Orgánica 15/1999, de 13 de diciembre, sobre protección de Datos de Carácter Personal (LOPD), <?php bloginfo('name'); ?>" informa a los usuarios de esta web mediante este documento del uso y tratamiento de los datos personales que faciliten o vayan a facilitar en su navegación y de la política de protección de datos que se aplicará sobre dichos datos.</p>
			<p><strong>II. Vías a través de las cuales se recaban datos personales. Finalidades del tratamiento.</strong></p>
			<p>• Formularios de contacto, peticiones de presupuesto y medios de comunicación tradicionales. Los datos personales recogidos serán objeto de tratamiento automatizado e incorporados al fichero denominado WEB <?php bloginfo('name'); ?>" del que <?php bloginfo('name'); ?>" es responsable. Asimismo, podrá facilitarnos sus datos a través de teléfono, correo electrónico y otros medios de comunicación indicados en la sección de Contacto. La finalidad del tratamiento de estos datos será la Gestión de los datos recibidos a través de formularios de la web para el Tratamiento de los mismos a las peticiones solicitadas por el usuario, inclusión en agenda de contactos, respuesta a preguntas, envío de Newsletter y comunicaciones electrónicas comerciales.</p>
			<p>Se informa que gestionará automatizadamente estos datos para la administración, ampliación y mejora de nuestros servicios así como para fines técnicos y comerciales sobre los servicios ofrecidos. En todo caso, los datos recogidos y tratados son únicamente los básicos para las finalidades señaladas anteriormente.</p>
			<p>El Usuario es responsable de la veracidad de sus datos, comprometiéndose a no introducir datos falsos y a proceder a la rectificación de los mismos si fuera necesario. El prestador pone a disposición del Usuario todos los medios para que pueda proceder a la modificación de sus datos mediante los formularios designados en nuestra web. El Usuario manifiesta que cuando no introduce sus datos personales sino los de un tercero están autorizados por éste para su introducción.</p>
			<p>El PRESTADOR quedará exonerado de responsabilidad en el caso de que la solicitud de muestra o corrección de datos se realice desde la dirección de correo electrónico que usted nos ha aportado a través de cualquiera de los formularios de la web, pues en ese caso presumirá que es el usuario quién la realiza. Los campos en los que figure un asterisco (*) son aquellos que requieren una respuesta obligatoria. De no ser cubiertos la consecuencia consiste en la imposibilidad de enviar la solicitud de información.</p>
			<p><strong>III. Ejercicio de Derechos de Protección de Datos (ARCO)</strong></p>
			<p>El usuario tiene derecho a solicitar y obtener gratuitamente información sobre sus datos de carácter personal sometidos a tratamiento, de su origen (que en nuestro caso serán siempre los formularios situados en la web) y de las comunicaciones que puedan afectar a los mismos. Los usuarios pueden dirigir una comunicación por escrito al domicilio social de <?php bloginfo('name'); ?>" o a la dirección de correo electrónico <a href="mailto:<?php echo mytheme_option( 'email' ); ?>"><?php echo mytheme_option( 'email' ); ?></a>, incluyendo en ambos casos fotocopia de su DNI u otro documento identificativo similar, para solicitar el ejercicio de los derechos de acceso, rectificación, cancelación y oposición.</p>
			<p><strong>IV. Consentimiento y revocación del usuario con fines informativos</strong></p>
			<p>A través de la casilla de marcación El usuario acepta nuestra política de privacidad y obtenemos su consentimiento para el envío de comunicaciones informativas sobre nuestros servicios y actividades así como para la contestación a las consultas formuladas por el usuario. Así mismo podrá en cualquier momento revocar el consentimiento prestado para fines de promoción y publicidad de nuestros servicios, boletines de noticias y el envío de comunicaciones comerciales electrónicas, dirigiendo un mail a la dirección <a href="mailto:<?php echo mytheme_option( 'email' ); ?>"><?php echo mytheme_option( 'email' ); ?></a> con el asunto BAJA LOPD, o dirigiéndose a nuestro domicilio en los términos definidos por nuestra empresa.</p>
	    </div>
	</section>
</div>

<?php get_footer(); ?>